<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>Xake.Dotnet</AssemblyName>
    <OutputType>Library</OutputType>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <TargetFrameworks>net462;netstandard2.0</TargetFrameworks>
    <Copyright>(c) OlegZee 2014-2025</Copyright>

    <PackageProjectUrl>https://github.com/xakebuild/Xake</PackageProjectUrl>
    <PackageIconUrl>https://github.com/xakebuild/Xake/raw/dev/Icon.png</PackageIconUrl>
    <Description>Xake build tool tasks for full .NET framework</Description>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="CommonLib.fs" />
    <Compile Include="ProcessExec.fs" />
    <Compile Include="DotNetFwk.fs" />
    <Compile Include="ResourceFileset.fs" />

    <Compile Include="DotnetTasks.fs" />
    <Compile Include="Dotnet.csc.fs" />
    <Compile Include="Dotnet.fsc.fs" />
    <Compile Include="Dotnet.resgen.fs" />
    <Compile Include="Dotnet.Msbuild.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\core\Xake.fsproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
    <PackageReference Include="Microsoft.Win32.Registry" Version="5.0.0" />
  </ItemGroup>
</Project>
